config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'

resources :posts do
  resources :comments
end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
     @post = Post.find(params[:post_id])
     @comment= @post.comments.create(comment_params)
     redirect_to post_path(@post)

  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Страничка о нас!'
    @text = 'Немного текста'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]


  def index
    @post = Post.all

  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])

  end


  def show
    @post = Post.find(params[:id])


  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: 'Пост успешно удален.'
  end


  def create
    # render plain: params[:post].inspect

    @post = Post.new(post_params)

    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end

  end

  private def post_params
  params.require(:post).permit(:title, :body)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
             
        <h5 class="my-0 mr-md-auto font-weight-bold">BLOGS</h5>
     

      <nav class="d-inline-flex mt-2 mt-md-1 ms-md-auto">
        <span class="p-2 text-dark"><%=link_to "Главная страница", home_path %></span>
         <span class="p-2 text-dark"><%=link_to "Добавление статьи", new_post_path %></span>
          <span class="p-2 text-dark"><%=link_to "О нас", about_path %></span>
      </nav>
         
      
    </div>
<div class="container">
    <%= yield %>
 </div>
  </body>
</html>

app/views/pages/about.html.erb
<h4> <%=@heading%></h4>
<p><%= @text %></p>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>


<%= form_for @post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any?%>
   <% @post.errors.full_messages.each do |msg|%>
    <div class='alert alert-danger'><%=msg%></div>
   <% end %>
<% end %>

<p>
    Название<br>
    <%= f.text_field(:title, {:class =>'form-control'}) %>

</p>

<p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class =>'form-control'}) %>

</p>

<p>
   
    <%=f.submit ({:class =>'btn btn-success'}) %>

</p>
<% end %>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post| %>
<div class="alert alert-light">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читать далее", post_path(post), :class => 'btn btn-primary' %>
</div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>


<%=form_for :post, url: posts_path do |f| %>
<% if @post.errors.any?%>
   <% @post.errors.full_messages.each do |msg|%>
    <div class='alert alert-danger'><%=msg%></div>
   <% end %>
<% end %>

<p>
    Название<br>
    <%= f.text_field(:title, {:class =>'form-control'}) %>

</p>

<p>
    Текст статьи<br>
    <%= f.text_area(:body, {:class =>'form-control'}) %>

</p>

<p>
   
     <%= f.submit("Сохранить пост", class: 'btn btn-success') %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class=>'btn btn-warning' %>
<br>
</br>
<%= button_to "Удалить", post_path(@post), method: :delete, onclick: "return confirm('Вы уверены, что хотите удалить этот пост?');", class: 'btn btn-danger' %>
<hr>

<h2>Все комментарии</h2>
<hr>
<% @post.comments.each do |comment| %>
<div class="lead">
    <p>
        <storng class="blockquote">
            <%=comment.username%>
        </storng>: <%=comment.body%>
    </p>
</div>
<% end %>


<h2>Добавление комментария</h2>

<%=form_for([@post, @post.comments.build]) do |f| %>

<p>
    Пользователь<br>
    <%= f.text_field(:username, {:class =>'form-control'}) %>

</p>

<p>
    Текст комментария<br>
    <%= f.text_area(:body, {:class =>'form-control'}) %>

</p>

<p>
   
     <%= f.submit("Добавить комментарий", class: 'btn btn-warning') %>

</p>
<% end %>